from langchain_core.messages import HumanMessage, AIMessage, BaseMessage
from langchain_core.tools import tool
from tavily import TavilyClient
from langgraph.graph import StateGraph, MessagesState, END
from langchain_openai import ChatOpenAI


# --------------------------------------------------
# LLM
# --------------------------------------------------

model = ChatOpenAI(
    api_key="api_key",
    base_url="base_url",
    model="poolside llm model"
)


tavily = TavilyClient(
    api_key="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"
)


# --------------------------------------------------
# Tools
# --------------------------------------------------

@tool
def parse_resume(text: str) -> str:
    """Extracts skills, roles, years of experience from resume text"""

    prompt = f"""
    Extract structured information such as:

    - Skills
    - Roles
    - Years of experience

    From this resume:

    {text}
    """

    return model.invoke(
        [HumanMessage(content=prompt)]
    ).content


@tool
def search_jobs_tavily(query: str) -> str:
    """Search for jobs using Tavily and returns search results"""

    results = tavily.search(query)

    print("Tavily results:")
    print(results)

    return results["results"]


# --------------------------------------------------
# Nodes
# --------------------------------------------------

def profile_node(state: MessagesState):

    # Get the latest message
    resume = state["messages"][-1].content

    # Call tool
    profile = parse_resume.invoke({
        "text": resume
    })

    # Return only the new message
    return {
        "messages": [
            AIMessage(
                content=f"Extracted Profile:\n{profile}"
            )
        ]
    }


def job_search_node(state: MessagesState):

    # Get profile generated by previous node
    profile = state["messages"][-1].content

    # Generate short search query
    query = model.invoke([
        HumanMessage(
            content=f"""
            Based on this profile, write a very short
            job search query.

            Profile:
            {profile}
            """
        )
    ]).content

    print("Search query:", query)

    # Search jobs
    jobs = search_jobs_tavily.invoke({
        "query": query
    })

    return {
        "messages": [
            AIMessage(
                content=f"Found jobs:\n{jobs}"
            )
        ]
    }


def matcher_node(state: MessagesState):

    # messages:
    # [-1] = jobs
    # [-2] = profile

    profile = state["messages"][-2].content
    jobs = state["messages"][-1].content

    prompt = f"""
    Given this candidate profile:

    {profile}

    Rank and recommend the top 3 jobs from:

    {jobs}

    Explain briefly why each job is a good match.
    """

    ranked = model.invoke([
        HumanMessage(content=prompt)
    ])

    return {
        "messages": [
            ranked
        ]
    }


def cover_letter_node(state: MessagesState):

    # messages:
    # [-1] = ranked jobs
    # [-3] = profile

    profile = state["messages"][-3].content
    best_job = state["messages"][-1].content

    prompt = f"""
    Write a personalized short cover letter for this job.

    Job Information:
    {best_job}

    Candidate Profile:
    {profile}
    """

    letter = model.invoke([
        HumanMessage(content=prompt)
    ])

    return {
        "messages": [
            letter
        ]
    }


# --------------------------------------------------
# LangGraph
# --------------------------------------------------

graph = StateGraph(MessagesState)

graph.add_node("profile", profile_node)
graph.add_node("search", job_search_node)
graph.add_node("match", matcher_node)
graph.add_node("cover", cover_letter_node)

graph.set_entry_point("profile")

graph.add_edge("profile", "search")
graph.add_edge("search", "match")
graph.add_edge("match", "cover")
graph.add_edge("cover", END)

app = graph.compile()


# --------------------------------------------------
# Run
# --------------------------------------------------

input_msg = HumanMessage(
    content="""
    I am a QA Engineer with total 18 years of experience,
    10 years of experience in manual testing and 8 years
    of experience in Robot Framework, Python-Selenium,
    Python-Playwright, XCUITest and Playwright AI testing.
    """
)

result = app.invoke({
    "messages": [input_msg]
})


print("\n---- Output ----\n")

for msg in result["messages"]:
    print(f"{type(msg).__name__}: {msg.content}\n")